---
    - name: Find our own instance ID. There is a better way to do this, but it requires ansible more modern than 2.9
      shell: /usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id
      register: instance_id_result
      changed_when: False

    - name: debug instance_id_result
      debug:
          var: instance_id_result

    - set_fact:
        instance_id: "{{ instance_id_result.stdout_lines[0]|trim() }}"

    - assert:
        that:
          - (instance_id | length) == 19
          - instance_id.startswith("i-")

    - name: Gather the rest of the instance info
      ec2_instance_info:
        region: "{{ aws_region }}"
        instance_ids:
          - "{{ instance_id }}"
      register: ec2_facts

    - name: Get root_device_name
      set_fact:
        root_device_name: "{{ ec2_facts.instances[0].root_device_name }}"

    - name: Debug root_device_name
      debug:
          var: root_device_name

    - name: Get block_device_mappings
      set_fact:
        block_device_mappings: "{{ ec2_facts.instances[0].block_device_mappings }}"

    - name: Debug block_device_mappings
      debug:
          var: block_device_mappings
