---
    - name: Get volume ID of root device
      set_fact:
        root_volume_id: "{{ block_device_mappings | selectattr('device_name', 'equalto', root_device_name) | map(attribute='ebs.volume_id') | list | first }}"

    - name: Debug root_volume_id
      debug:
        var: root_volume_id

    - name: Collect volume info, which also includes critical tag data. If we didn't need the tags, we could just use the block_device_mappings.
      ec2_vol_info:
        region: "{{ aws_region }}"
        filters:
          attachment.instance-id: "{{ instance_id }}"
      register: volume_info

    - name: Debug volume_info
      debug:
          var: volume_info

    - name: Exclude root volume from list of volumes to configure
      set_fact:
        secondary_volumes: "{{ volume_info.volumes | rejectattr('id', 'equalto', root_volume_id) | list }}"

    - name: Debug secondary_volumes
      debug:
          var: secondary_volumes
